builds:
  - id: basechange
    main: ./cmd/basechange
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

checksum:
  algorithm: sha256

archives:
  - id: basechange
    builds:
      - basechange
    format: tar.gz
