name: Test, build, and release

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write

env:
  GO_VERSION: '1.21.3'

jobs:
  test_build_release:
    name: Test, publish, and release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Export GOBIN
        uses: actions/setup-go@v4
        with:
          go-version: '${{env.GO_VERSION}}'

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        if: startsWith(github.ref, 'refs/tags/v') # Only release for tagged commits.
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
